stages:
    - build
    - deploy

variables:
    DOCKER_IMAGE: dockerusername/dockerimage
    DOCKER_TAG: latest
    SSH_USER: ubuntu
    SSH_HOST: <EC2_PUBLIC_IP>         
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

before_script:
    - apk add --no-cache openssh-client docker-cli 

build:
    stage: build
    image: docker:latest 
    services:
        - docker:dind
    script:
        - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
    stage: deploy
    image: alpine:latest
    before_script:
        - apk add --no-cache openssh-client
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

    script:
    - ssh $SSH_USER@$SSH_HOST "docker pull $DOCKER_IMAGE:$DOCKER_TAG && docker stop flutter-app || true && docker rm flutter-app || true && docker run -d --name flutter-app -p 8082:80 $DOCKER_IMAGE:$DOCKER_TAG
         







